"""empty message

Revision ID: 411b0d0bff79
Revises: c89a5035b3ad
Create Date: 2024-07-14 18:40:30.109847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '411b0d0bff79'
down_revision = 'c89a5035b3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('security_answer_2')
        batch_op.drop_column('security_question_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_question_2', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('security_answer_2', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
