"""empty message

Revision ID: c89a5035b3ad
Revises: afa0e193ae11
Create Date: 2024-07-14 17:25:42.222183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89a5035b3ad'
down_revision = 'afa0e193ae11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours_worked', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('tax_deduction', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_column('tax_deduction')
        batch_op.drop_column('hourly_rate')
        batch_op.drop_column('hours_worked')

    # ### end Alembic commands ###
